#!/bin/bash
#set -x

#12) Vérifiez que le serveur avec l’adresse IP 10.51.1.253 est touchable depuis votre poste

ping -c 4 10.51.1.253

#script 
#server="10.51.1.253"
#ping -c1 -W1 -q $server &>/dev/null
#status=$( echo $? )
#if [ $status == 0 ] ; then
#	echo "server is up"
#else
#	echo "server is down"
#fi

